package com.dayzeeco.dayzee.model

import android.os.Parcelable
import com.google.gson.annotations.SerializedName
import kotlinx.android.parcel.Parcelize
val listOfHeaders : List<String> = listOf("Sport", "Music", "Esport", "Youtubers", "Religion", "Culture", "Movies & Series", "Shopping", "Holidays", "Interesting Calendars")
val listOfCategories : List<Categories> = listOf(
	Categories("Sport", "Football"),
	Categories("Sport", "Tennis"),
	Categories("Sport", "Basket"),
	Categories("Sport", "Handball"),
	Categories("Sport", "Sport US"),
	Categories("Sport", "Rugby"),
	Categories("Sport", "Cyclisme"),
	Categories("Sport", "Auto/Moto"),
	Categories("Sport", "Golf"),
	Categories("Sport", "Ski"),
	Categories("Sport", "Athletisme"),
	Categories("Sport", "Boxe"),
	Categories("Sport", "Natation"),
	Categories("Sport", "Judo"),
	Categories("Sport", "Voile"),
	Categories("Sport", "Surf"),
	Categories("Music", "Classique & Opera"),
	Categories("Music", "Electro"),
	Categories("Music", "Rap & Hip-Hop"),
	Categories("Music", "Jazz"),
	Categories("Music", "Music of the world"),
	Categories("Music", "Pop rock & Folk"),
	Categories("Music", "Hard rock & Metal"),
	Categories("Music", "Reggae"),
	Categories("Music", "Blues & Country"),
	Categories("Music", "Gospel"),
	Categories("Music", "RnB"),
	Categories("Music", "Soul"),
	Categories("Music", "Funk"),
	Categories("Esport", "Fifa"),
	Categories("Esport", "Counter Strike"),
	Categories("Esport", "Clash Royal"),
	Categories("Esport", "League of Legends"),
	Categories("Esport", "Hearthstone"),
	Categories("Esport", "Dota"),
	Categories("Esport", "Overwatch"),
	Categories("Esport", "Rainbow Six Siege"),
	Categories("Esport", "Rocket League"),
	Categories("Esport", "PES"),
	Categories("Esport", "Vainglory"),
	Categories("Esport", "Street Fighter"),
	Categories("Esport", "COD"),
	Categories("Esport", "Tekken"),
	Categories("Esport", "Clash of Clans"),
	Categories("Youtubers", "Twitch Gamers"),
	Categories("Youtubers", "Beauty"),
	Categories("Youtubers", "Business"),
	Categories("Youtubers", "Cinema"),
	Categories("Youtubers", "Courses"),
	Categories("Youtubers", "Cooking"),
	Categories("Youtubers", "Fiction"),
	Categories("Youtubers", "Humour"),
	Categories("Youtubers", "Computers"),
	Categories("Youtubers", "Video Games"),
	Categories("Youtubers", "Reading"),
	Categories("Youtubers", "Lifestyle"),
	Categories("Youtubers", "Magic"),
	Categories("Youtubers", "Manga"),
	Categories("Youtubers", "Music"),
	Categories("Youtubers", "Photography"),
	Categories("Youtubers", "Politic"),
	Categories("Youtubers", "Relaxation"),
	Categories("Youtubers", "Dating"),
	Categories("Youtubers", "Science"),
	Categories("Youtubers", "Sport"),
	Categories("Youtubers", "Vlog"),
	Categories("Religion", "Christianity"),
	Categories("Religion", "Judaism"),
	Categories("Religion", "Islam"),
	Categories("Religion", "Buddhism"),
	Categories("Religion", "Hinduism"),
	Categories("Religion", "Others"),
	Categories("Culture", "Theater"),
	Categories("Culture", "Exposition"),
	Categories("Culture", "Dance"),
	Categories("Culture", "Spectacle"),
	Categories("Culture", "Circus"),
	Categories("Culture", "For the children"),
	Categories("Culture", "Salon"),
	Categories("Culture", "Sport"),
	Categories("Culture", "Festival"),
	Categories("Culture", "Courses"),
	Categories("Movies & Series", "Cinema outings"),
	Categories("Movies & Series", "Series outings"),
	Categories("Movies & Series", "Netflix"),
	Categories("Shopping", "Woman"),
	Categories("Shopping", "Man"),
	Categories("Shopping", "Children"),
	Categories("Shopping", "Sneakers"),
	Categories("Shopping", "Hi-Tech"),
	Categories("Shopping", "Games"),
	Categories("Shopping", "Auto"),
	Categories("Holidays", "France"),
	Categories("Holidays", "UK"),
	Categories("Holidays", "USA"),
	Categories("Holidays", "Germany"),
	Categories("Holidays", "Italy"),
	Categories("Holidays", "Spain"),
	Categories("Interesting Calendars", "Politic"),
	Categories("Interesting Calendars", "Economic"),
	Categories("Interesting Calendars", "Culinary"),
	Categories("Interesting Calendars", "Nature"),
	Categories("Interesting Calendars", "Astronomy"),
	Categories("Interesting Calendars", "Astrology")
)

@Parcelize
data class Categories (
	@SerializedName("category") val category : String,
	@SerializedName("subcategory") val subcategory : String
) : Parcelable